import streamlit as st
from pptx import Presentation
from pptx.enum.shapes import PP_PLACEHOLDER
import io
import json
from groq import Groq

# --- Page Configuration ---
st.set_page_config(
    page_title="AI Presentation Architect",
    page_icon="🚀",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- Dynamic Model Fetching ---
@st.cache_data(ttl=3600)
def get_available_groq_models(_client):
    try:
        model_list = _client.models.list().data
        active_models = [m for m in model_list if m.active and "embedding" not in m.id]
        return sorted([model.id for model in active_models])
    except Exception as e:
        st.warning(f"Could not fetch live model list. Using fallback. Error: {e}")
        return ["llama3-8b-8192", "mixtral-8x7b-32768", "gemma2-9b-it"]

# --- Core Presentation Logic (Multi-slide support) ---
def create_presentation_from_template(template_file, main_title, slides_content):
    """
    Creates a new presentation, clearing the template and adding a title slide
    plus multiple content slides.
    """
    try:
        prs = Presentation(template_file)
    except Exception as e:
        st.error(f"❌ Error reading the template file: {e}"); return None

    try:
        sldIdLst = prs.slides._sldIdLst
        rIds_to_remove = [sldId.rId for sldId in sldIdLst]
        for rId in rIds_to_remove:
            prs.part.drop_rel(rId)
        sldIdLst.clear()
    except Exception as e:
        st.error(f"❌ Could not clean the template file. Error: {e}"); return None

    # Add Main Title Slide
    if len(prs.slide_layouts) > 0:
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        if slide.shapes.title: slide.shapes.title.text = main_title
        try: slide.placeholders[1].text = "Generated by AI Presentation Architect"
        except (KeyError, IndexError): pass
    else:
        st.warning("⚠️ Template must have a Title Slide Layout."); return None

    # Loop through and add all content slides
    for content in slides_content:
        if len(prs.slide_layouts) > 1:
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            if slide.shapes.title: slide.shapes.title.text = content.get("title", "No Title")
            
            body_shape = next((shape for shape in slide.placeholders if shape.placeholder_format.type == PP_PLACEHOLDER.BODY), None)
            
            if body_shape:
                tf = body_shape.text_frame; tf.clear()
                content_bullets = content.get("bullets", [])
                if content_bullets:
                    p = tf.paragraphs[0]; p.text = content_bullets[0]; p.level = 0
                    for bullet_text in content_bullets[1:]:
                        p = tf.add_paragraph(); p.text = bullet_text; p.level = 0
            else:
                st.warning("⚠️ Could not find a 'Body' placeholder on a content slide.")
        else:
            st.error("❌ Template needs a 'Title and Content' Layout to add content slides."); break

    bio = io.BytesIO(); prs.save(bio); bio.seek(0); return bio

# --- Groq LLM Content Generation (JSON mode) ---
def generate_content_with_groq(api_key, model, topic, num_slides):
    if not api_key: st.error("Groq API key not configured."); return None
    client = Groq(api_key=api_key)
    
    system_prompt = f"""
    You are an expert presentation creator. Your response MUST be a valid JSON array of objects and nothing else.
    Each object represents a single slide and must have two keys: "title" (a string for the slide's title) and "bullets" (an array of strings for the slide's bullet points).
    Generate exactly {num_slides} unique slides about the topic: '{topic}'.
    """
    
    try:
        chat_completion = client.chat.completions.create(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Generate {num_slides} slides about {topic}."}
            ],
            model=model,
            temperature=0.7,
            response_format={"type": "json_object"},
        )
        # Groq's JSON mode often wraps the array in a root object, so we need to find the array.
        response_text = chat_completion.choices[0].message.content
        response_data = json.loads(response_text)
        
        # Find the first value in the JSON object that is a list (this will be our slide array)
        for key, value in response_data.items():
            if isinstance(value, list):
                return value
        st.error("AI did not return the expected slide array format."); return None

    except Exception as e:
        st.error(f"Groq API Error: {e}"); return None

# --- UI ---
st.title("🚀 AI Presentation Architect")
st.markdown("Instantly create multi-slide presentations using a live list of AI models.")

# State Init
if 'generated_slides' not in st.session_state: st.session_state.generated_slides = []
if 'show_preview' not in st.session_state: st.session_state.show_preview = False
if 'ppt_download_buffer' not in st.session_state: st.session_state.ppt_download_buffer = None

with st.sidebar:
    st.header("⚙️ Configuration")
    with st.expander("1️⃣ Upload Template", expanded=True):
        uploaded_template = st.file_uploader("Upload a .pptx file", type="pptx", label_visibility="collapsed")
    with st.expander("2️⃣ Define Content", expanded=True):
        presentation_title = st.text_input("Main Presentation Title", "Quarterly Business Review")
        st.subheader("AI Content Engine")
        try:
            groq_api_key = st.secrets["GROQ_API_KEY"]; groq_client = Groq(api_key=groq_api_key)
            st.success("Groq API key loaded.", icon="✅")
        except:
            st.error("Groq API key not found in secrets."); groq_api_key = None; groq_client = None

        if groq_client:
            available_models = get_available_groq_models(groq_client)
            selected_model_id = st.selectbox("Select AI Model (Live)", options=available_models)
            
            topic = st.text_input("Presentation Topic", "The Future of Renewable Energy")
            num_slides = st.number_input("Number of Content Slides", min_value=1, max_value=50, value=3)

            if st.button("✨ Generate Content"):
                with st.spinner(f"🤖 Calling {selected_model_id} to generate {num_slides} slides..."):
                    generated_data = generate_content_with_groq(groq_api_key, selected_model_id, topic, num_slides)
                    if generated_data:
                        st.session_state.generated_slides = generated_data
                        st.session_state.show_preview = False
                        st.session_state.ppt_download_buffer = None
                        st.toast(f"{len(generated_data)} slides generated!", icon="🎉"); st.rerun()
        else:
            st.info("Configure your Groq API key to enable content generation.")

if not uploaded_template:
    st.info("👈 Please upload your company's .pptx template to begin.")
else:
    if st.session_state.ppt_download_buffer:
        st.success("✅ Your presentation is ready to download!")
        st.download_button(
            label="📥 Download Presentation (.pptx)", data=st.session_state.ppt_download_buffer,
            file_name=f"{st.session_state.get('presentation_title', 'presentation').replace(' ', '_').lower()}.pptx",
            mime="application/vnd.openxmlformats-officedocument.presentationml.presentation", use_container_width=True
        )
        st.markdown("---")
        
    st.header("🎬 Preview and Generate")
    if not st.session_state.show_preview and st.session_state.generated_slides:
        if st.button("📝 Preview My Presentation", use_container_width=True):
            st.session_state.show_preview = True; st.session_state.ppt_download_buffer = None; st.rerun()

    if st.session_state.show_preview:
        st.subheader("Content Preview")
        with st.container(border=True):
            st.markdown(f"##### Main Title Slide\n- **Title:** `{presentation_title}`")
            st.markdown("---")
            for i, slide_content in enumerate(st.session_state.generated_slides, 1):
                st.markdown(f"##### Content Slide {i}\n- **Title:** `{slide_content.get('title', 'N/A')}`\n- **Body:**")
                for bullet in slide_content.get('bullets', []):
                    st.markdown(f"  - {bullet}")
                st.markdown("---")
        st.divider()
        if st.button("✅ Confirm & Generate PPT", type="primary", use_container_width=True):
            with st.spinner("Assembling your presentation..."):
                generated_ppt_io = create_presentation_from_template(uploaded_template, presentation_title, st.session_state.generated_slides)
                if generated_ppt_io:
                    st.session_state.presentation_title = presentation_title
                    st.session_state.ppt_download_buffer = generated_ppt_io
                    st.session_state.show_preview = False
                    st.rerun()
